### ISSUE TITLE
PlutoIPTV-for-TVH question

### ISSUE THREAD

**Issue by ReenigneArcher** [zang74/TuneInScraper#1]
This is actually for your repository here: https://github.com/zang74/PlutoIPTV-for-TVH

I would have opened an issue there but it wasn't an option. I've written a similar script (https://github.com/ReenigneArcher/web2tv)

How did you determine the max epg time is 10 hours?

In my script I get quite a few more airings if I collect more hours.

I just ran it... and with 10 hours I got 4067 airings... with 12 hours I got 4566 airings. Anything over 12 hours returns the same 4566 airings.

**Comment by zang74** [comment]
I've mostly abandoned PlutoIPTV-for-TVH this as the streams don't seem to get handled all that well at the TVH end. Streams "pause" when commercials are inserted by the server, and often the entire stream switches to a difference channel when it eventually comes back (most often, it seems, in Spanish).

That said, at the time I was only reliably getting 8 full hours for every channel when the EPG was pulled. Anything longer would be spotty, and some channels missing later data. In doing so, anyone additionally using the script and choosing to max out the EPG to 10 hours may believe that means they only need to run the script every 10 hours, which would effectively leave vast patches of missing data. This is made worse with TVH as its default is to run EPG every 12 hours (00:04 and 12:04 every day). A user needs to run the script every hour if they want a reliable, searchable EPG.

**Comment by ReenigneArcher** [comment]
@zang74 thank you, that explanation makes sense and matches my what I am seeing. Some channels don't have information out to 12 hours in my testing as well, but instead around 10.5 to 11 hours.

I had the same problem with the streams. I'm not using TVH and not sure exactly how it works, but I was able to solve the commercial problem by playing the streams with streamlink (https://github.com/streamlink/streamlink). It's available for linux so maybe it can solve the issue for you.

They have a plugin specifically for pluto tv. Although you need to change the stream url to `http://pluto.tv/live-tv/<channelSlug>`
